//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWA.Services.WSGO_VA {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.integraCir2k.gjc.com.br/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensagemListVO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(notaTituloVO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(notaVO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mensagemVO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(duplicataNotaVO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(itemNotaVO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(representanteVO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cabecalhoNotaVO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.integraCir2k.gjc.com.br/")]
    public abstract partial class abstractVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.integraCir2k.gjc.com.br/")]
    public partial class mensagemListVO : abstractVO {
        
        private mensagemVO[] mensagemVOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mensagemVO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public mensagemVO[] mensagemVO {
            get {
                return this.mensagemVOField;
            }
            set {
                this.mensagemVOField = value;
                this.RaisePropertyChanged("mensagemVO");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.integraCir2k.gjc.com.br/")]
    public partial class mensagemVO : abstractVO {
        
        private int idMensagemField;
        
        private bool idMensagemFieldSpecified;
        
        private int clTipoField;
        
        private bool clTipoFieldSpecified;
        
        private string dsDescricaoField;
        
        private int dsOrigemField;
        
        private bool dsOrigemFieldSpecified;
        
        private System.DateTime dtEnvioField;
        
        private bool dtEnvioFieldSpecified;
        
        private notaVO notaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idMensagem {
            get {
                return this.idMensagemField;
            }
            set {
                this.idMensagemField = value;
                this.RaisePropertyChanged("idMensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idMensagemSpecified {
            get {
                return this.idMensagemFieldSpecified;
            }
            set {
                this.idMensagemFieldSpecified = value;
                this.RaisePropertyChanged("idMensagemSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int clTipo {
            get {
                return this.clTipoField;
            }
            set {
                this.clTipoField = value;
                this.RaisePropertyChanged("clTipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clTipoSpecified {
            get {
                return this.clTipoFieldSpecified;
            }
            set {
                this.clTipoFieldSpecified = value;
                this.RaisePropertyChanged("clTipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dsDescricao {
            get {
                return this.dsDescricaoField;
            }
            set {
                this.dsDescricaoField = value;
                this.RaisePropertyChanged("dsDescricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int dsOrigem {
            get {
                return this.dsOrigemField;
            }
            set {
                this.dsOrigemField = value;
                this.RaisePropertyChanged("dsOrigem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dsOrigemSpecified {
            get {
                return this.dsOrigemFieldSpecified;
            }
            set {
                this.dsOrigemFieldSpecified = value;
                this.RaisePropertyChanged("dsOrigemSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime dtEnvio {
            get {
                return this.dtEnvioField;
            }
            set {
                this.dtEnvioField = value;
                this.RaisePropertyChanged("dtEnvio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtEnvioSpecified {
            get {
                return this.dtEnvioFieldSpecified;
            }
            set {
                this.dtEnvioFieldSpecified = value;
                this.RaisePropertyChanged("dtEnvioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public notaVO nota {
            get {
                return this.notaField;
            }
            set {
                this.notaField = value;
                this.RaisePropertyChanged("nota");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.integraCir2k.gjc.com.br/")]
    public partial class notaVO : abstractVO {
        
        private int idNotaField;
        
        private bool idNotaFieldSpecified;
        
        private int idMensagemField;
        
        private bool idMensagemFieldSpecified;
        
        private string cdCodigoEstabelecimentoField;
        
        private string dsSerieField;
        
        private string cdChaveAcessoField;
        
        private string cdLocalDepField;
        
        private string cdLocalPagField;
        
        private int cdOrigemReciboField;
        
        private bool cdOrigemReciboFieldSpecified;
        
        private string cdParcelaField;
        
        private string cdReciboField;
        
        private int clSituacaoField;
        
        private bool clSituacaoFieldSpecified;
        
        private int clTpMovimentoField;
        
        private bool clTpMovimentoFieldSpecified;
        
        private string dsUsrField;
        
        private System.DateTime dtCreditoField;
        
        private bool dtCreditoFieldSpecified;
        
        private System.DateTime dtMovField;
        
        private bool dtMovFieldSpecified;
        
        private System.DateTime dtTransacaoField;
        
        private bool dtTransacaoFieldSpecified;
        
        private string dvReciboField;
        
        private decimal vlDescontoField;
        
        private bool vlDescontoFieldSpecified;
        
        private decimal vlJurosField;
        
        private bool vlJurosFieldSpecified;
        
        private decimal vlPagoField;
        
        private bool vlPagoFieldSpecified;
        
        private string nrNotaFisField;
        
        private notaTituloVO[] notaTituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idNota {
            get {
                return this.idNotaField;
            }
            set {
                this.idNotaField = value;
                this.RaisePropertyChanged("idNota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idNotaSpecified {
            get {
                return this.idNotaFieldSpecified;
            }
            set {
                this.idNotaFieldSpecified = value;
                this.RaisePropertyChanged("idNotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idMensagem {
            get {
                return this.idMensagemField;
            }
            set {
                this.idMensagemField = value;
                this.RaisePropertyChanged("idMensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idMensagemSpecified {
            get {
                return this.idMensagemFieldSpecified;
            }
            set {
                this.idMensagemFieldSpecified = value;
                this.RaisePropertyChanged("idMensagemSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cdCodigoEstabelecimento {
            get {
                return this.cdCodigoEstabelecimentoField;
            }
            set {
                this.cdCodigoEstabelecimentoField = value;
                this.RaisePropertyChanged("cdCodigoEstabelecimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string dsSerie {
            get {
                return this.dsSerieField;
            }
            set {
                this.dsSerieField = value;
                this.RaisePropertyChanged("dsSerie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cdChaveAcesso {
            get {
                return this.cdChaveAcessoField;
            }
            set {
                this.cdChaveAcessoField = value;
                this.RaisePropertyChanged("cdChaveAcesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string cdLocalDep {
            get {
                return this.cdLocalDepField;
            }
            set {
                this.cdLocalDepField = value;
                this.RaisePropertyChanged("cdLocalDep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string cdLocalPag {
            get {
                return this.cdLocalPagField;
            }
            set {
                this.cdLocalPagField = value;
                this.RaisePropertyChanged("cdLocalPag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int cdOrigemRecibo {
            get {
                return this.cdOrigemReciboField;
            }
            set {
                this.cdOrigemReciboField = value;
                this.RaisePropertyChanged("cdOrigemRecibo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cdOrigemReciboSpecified {
            get {
                return this.cdOrigemReciboFieldSpecified;
            }
            set {
                this.cdOrigemReciboFieldSpecified = value;
                this.RaisePropertyChanged("cdOrigemReciboSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string cdParcela {
            get {
                return this.cdParcelaField;
            }
            set {
                this.cdParcelaField = value;
                this.RaisePropertyChanged("cdParcela");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string cdRecibo {
            get {
                return this.cdReciboField;
            }
            set {
                this.cdReciboField = value;
                this.RaisePropertyChanged("cdRecibo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int clSituacao {
            get {
                return this.clSituacaoField;
            }
            set {
                this.clSituacaoField = value;
                this.RaisePropertyChanged("clSituacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clSituacaoSpecified {
            get {
                return this.clSituacaoFieldSpecified;
            }
            set {
                this.clSituacaoFieldSpecified = value;
                this.RaisePropertyChanged("clSituacaoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int clTpMovimento {
            get {
                return this.clTpMovimentoField;
            }
            set {
                this.clTpMovimentoField = value;
                this.RaisePropertyChanged("clTpMovimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clTpMovimentoSpecified {
            get {
                return this.clTpMovimentoFieldSpecified;
            }
            set {
                this.clTpMovimentoFieldSpecified = value;
                this.RaisePropertyChanged("clTpMovimentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string dsUsr {
            get {
                return this.dsUsrField;
            }
            set {
                this.dsUsrField = value;
                this.RaisePropertyChanged("dsUsr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public System.DateTime dtCredito {
            get {
                return this.dtCreditoField;
            }
            set {
                this.dtCreditoField = value;
                this.RaisePropertyChanged("dtCredito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtCreditoSpecified {
            get {
                return this.dtCreditoFieldSpecified;
            }
            set {
                this.dtCreditoFieldSpecified = value;
                this.RaisePropertyChanged("dtCreditoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public System.DateTime dtMov {
            get {
                return this.dtMovField;
            }
            set {
                this.dtMovField = value;
                this.RaisePropertyChanged("dtMov");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtMovSpecified {
            get {
                return this.dtMovFieldSpecified;
            }
            set {
                this.dtMovFieldSpecified = value;
                this.RaisePropertyChanged("dtMovSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public System.DateTime dtTransacao {
            get {
                return this.dtTransacaoField;
            }
            set {
                this.dtTransacaoField = value;
                this.RaisePropertyChanged("dtTransacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtTransacaoSpecified {
            get {
                return this.dtTransacaoFieldSpecified;
            }
            set {
                this.dtTransacaoFieldSpecified = value;
                this.RaisePropertyChanged("dtTransacaoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string dvRecibo {
            get {
                return this.dvReciboField;
            }
            set {
                this.dvReciboField = value;
                this.RaisePropertyChanged("dvRecibo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public decimal vlDesconto {
            get {
                return this.vlDescontoField;
            }
            set {
                this.vlDescontoField = value;
                this.RaisePropertyChanged("vlDesconto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vlDescontoSpecified {
            get {
                return this.vlDescontoFieldSpecified;
            }
            set {
                this.vlDescontoFieldSpecified = value;
                this.RaisePropertyChanged("vlDescontoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public decimal vlJuros {
            get {
                return this.vlJurosField;
            }
            set {
                this.vlJurosField = value;
                this.RaisePropertyChanged("vlJuros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vlJurosSpecified {
            get {
                return this.vlJurosFieldSpecified;
            }
            set {
                this.vlJurosFieldSpecified = value;
                this.RaisePropertyChanged("vlJurosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public decimal vlPago {
            get {
                return this.vlPagoField;
            }
            set {
                this.vlPagoField = value;
                this.RaisePropertyChanged("vlPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vlPagoSpecified {
            get {
                return this.vlPagoFieldSpecified;
            }
            set {
                this.vlPagoFieldSpecified = value;
                this.RaisePropertyChanged("vlPagoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string nrNotaFis {
            get {
                return this.nrNotaFisField;
            }
            set {
                this.nrNotaFisField = value;
                this.RaisePropertyChanged("nrNotaFis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("notaTitulo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public notaTituloVO[] notaTitulo {
            get {
                return this.notaTituloField;
            }
            set {
                this.notaTituloField = value;
                this.RaisePropertyChanged("notaTitulo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.integraCir2k.gjc.com.br/")]
    public partial class notaTituloVO : abstractVO {
        
        private int idNotaField;
        
        private bool idNotaFieldSpecified;
        
        private int cdSequenciaField;
        
        private bool cdSequenciaFieldSpecified;
        
        private string cdTituloACRField;
        
        private int clStatusField;
        
        private bool clStatusFieldSpecified;
        
        private System.DateTime dtPagtoField;
        
        private bool dtPagtoFieldSpecified;
        
        private decimal vlPagoField;
        
        private bool vlPagoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idNota {
            get {
                return this.idNotaField;
            }
            set {
                this.idNotaField = value;
                this.RaisePropertyChanged("idNota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idNotaSpecified {
            get {
                return this.idNotaFieldSpecified;
            }
            set {
                this.idNotaFieldSpecified = value;
                this.RaisePropertyChanged("idNotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cdSequencia {
            get {
                return this.cdSequenciaField;
            }
            set {
                this.cdSequenciaField = value;
                this.RaisePropertyChanged("cdSequencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cdSequenciaSpecified {
            get {
                return this.cdSequenciaFieldSpecified;
            }
            set {
                this.cdSequenciaFieldSpecified = value;
                this.RaisePropertyChanged("cdSequenciaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cdTituloACR {
            get {
                return this.cdTituloACRField;
            }
            set {
                this.cdTituloACRField = value;
                this.RaisePropertyChanged("cdTituloACR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int clStatus {
            get {
                return this.clStatusField;
            }
            set {
                this.clStatusField = value;
                this.RaisePropertyChanged("clStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clStatusSpecified {
            get {
                return this.clStatusFieldSpecified;
            }
            set {
                this.clStatusFieldSpecified = value;
                this.RaisePropertyChanged("clStatusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime dtPagto {
            get {
                return this.dtPagtoField;
            }
            set {
                this.dtPagtoField = value;
                this.RaisePropertyChanged("dtPagto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtPagtoSpecified {
            get {
                return this.dtPagtoFieldSpecified;
            }
            set {
                this.dtPagtoFieldSpecified = value;
                this.RaisePropertyChanged("dtPagtoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal vlPago {
            get {
                return this.vlPagoField;
            }
            set {
                this.vlPagoField = value;
                this.RaisePropertyChanged("vlPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vlPagoSpecified {
            get {
                return this.vlPagoFieldSpecified;
            }
            set {
                this.vlPagoFieldSpecified = value;
                this.RaisePropertyChanged("vlPagoSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.integraCir2k.gjc.com.br/")]
    public partial class duplicataNotaVO : abstractVO {
        
        private int idNotaField;
        
        private bool idNotaFieldSpecified;
        
        private string cdCodigoEspecieField;
        
        private int cdCodigoVencimentoField;
        
        private bool cdCodigoVencimentoFieldSpecified;
        
        private int codSeqDoctoField;
        
        private bool codSeqDoctoFieldSpecified;
        
        private string dsParcelaField;
        
        private System.DateTime dtDescontoField;
        
        private bool dtDescontoFieldSpecified;
        
        private System.DateTime dtVencimentoField;
        
        private bool dtVencimentoFieldSpecified;
        
        private decimal vlAcumuladoField;
        
        private bool vlAcumuladoFieldSpecified;
        
        private decimal vlComissaoField;
        
        private bool vlComissaoFieldSpecified;
        
        private decimal vlDescontoField;
        
        private bool vlDescontoFieldSpecified;
        
        private decimal vlParcelarField;
        
        private bool vlParcelarFieldSpecified;
        
        private decimal vlSaldoField;
        
        private bool vlSaldoFieldSpecified;
        
        private decimal qtdSaldoField;
        
        private bool qtdSaldoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idNota {
            get {
                return this.idNotaField;
            }
            set {
                this.idNotaField = value;
                this.RaisePropertyChanged("idNota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idNotaSpecified {
            get {
                return this.idNotaFieldSpecified;
            }
            set {
                this.idNotaFieldSpecified = value;
                this.RaisePropertyChanged("idNotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cdCodigoEspecie {
            get {
                return this.cdCodigoEspecieField;
            }
            set {
                this.cdCodigoEspecieField = value;
                this.RaisePropertyChanged("cdCodigoEspecie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int cdCodigoVencimento {
            get {
                return this.cdCodigoVencimentoField;
            }
            set {
                this.cdCodigoVencimentoField = value;
                this.RaisePropertyChanged("cdCodigoVencimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cdCodigoVencimentoSpecified {
            get {
                return this.cdCodigoVencimentoFieldSpecified;
            }
            set {
                this.cdCodigoVencimentoFieldSpecified = value;
                this.RaisePropertyChanged("cdCodigoVencimentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int codSeqDocto {
            get {
                return this.codSeqDoctoField;
            }
            set {
                this.codSeqDoctoField = value;
                this.RaisePropertyChanged("codSeqDocto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codSeqDoctoSpecified {
            get {
                return this.codSeqDoctoFieldSpecified;
            }
            set {
                this.codSeqDoctoFieldSpecified = value;
                this.RaisePropertyChanged("codSeqDoctoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string dsParcela {
            get {
                return this.dsParcelaField;
            }
            set {
                this.dsParcelaField = value;
                this.RaisePropertyChanged("dsParcela");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime dtDesconto {
            get {
                return this.dtDescontoField;
            }
            set {
                this.dtDescontoField = value;
                this.RaisePropertyChanged("dtDesconto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtDescontoSpecified {
            get {
                return this.dtDescontoFieldSpecified;
            }
            set {
                this.dtDescontoFieldSpecified = value;
                this.RaisePropertyChanged("dtDescontoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime dtVencimento {
            get {
                return this.dtVencimentoField;
            }
            set {
                this.dtVencimentoField = value;
                this.RaisePropertyChanged("dtVencimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtVencimentoSpecified {
            get {
                return this.dtVencimentoFieldSpecified;
            }
            set {
                this.dtVencimentoFieldSpecified = value;
                this.RaisePropertyChanged("dtVencimentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal vlAcumulado {
            get {
                return this.vlAcumuladoField;
            }
            set {
                this.vlAcumuladoField = value;
                this.RaisePropertyChanged("vlAcumulado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vlAcumuladoSpecified {
            get {
                return this.vlAcumuladoFieldSpecified;
            }
            set {
                this.vlAcumuladoFieldSpecified = value;
                this.RaisePropertyChanged("vlAcumuladoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal vlComissao {
            get {
                return this.vlComissaoField;
            }
            set {
                this.vlComissaoField = value;
                this.RaisePropertyChanged("vlComissao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vlComissaoSpecified {
            get {
                return this.vlComissaoFieldSpecified;
            }
            set {
                this.vlComissaoFieldSpecified = value;
                this.RaisePropertyChanged("vlComissaoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal vlDesconto {
            get {
                return this.vlDescontoField;
            }
            set {
                this.vlDescontoField = value;
                this.RaisePropertyChanged("vlDesconto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vlDescontoSpecified {
            get {
                return this.vlDescontoFieldSpecified;
            }
            set {
                this.vlDescontoFieldSpecified = value;
                this.RaisePropertyChanged("vlDescontoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public decimal vlParcelar {
            get {
                return this.vlParcelarField;
            }
            set {
                this.vlParcelarField = value;
                this.RaisePropertyChanged("vlParcelar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vlParcelarSpecified {
            get {
                return this.vlParcelarFieldSpecified;
            }
            set {
                this.vlParcelarFieldSpecified = value;
                this.RaisePropertyChanged("vlParcelarSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public decimal vlSaldo {
            get {
                return this.vlSaldoField;
            }
            set {
                this.vlSaldoField = value;
                this.RaisePropertyChanged("vlSaldo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vlSaldoSpecified {
            get {
                return this.vlSaldoFieldSpecified;
            }
            set {
                this.vlSaldoFieldSpecified = value;
                this.RaisePropertyChanged("vlSaldoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal qtdSaldo {
            get {
                return this.qtdSaldoField;
            }
            set {
                this.qtdSaldoField = value;
                this.RaisePropertyChanged("qtdSaldo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool qtdSaldoSpecified {
            get {
                return this.qtdSaldoFieldSpecified;
            }
            set {
                this.qtdSaldoFieldSpecified = value;
                this.RaisePropertyChanged("qtdSaldoSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.integraCir2k.gjc.com.br/")]
    public partial class itemNotaVO : abstractVO {
        
        private int idNotaField;
        
        private bool idNotaFieldSpecified;
        
        private string cdCodigoItemField;
        
        private int cdNumeroSequenciaField;
        
        private bool cdNumeroSequenciaFieldSpecified;
        
        private string codTabelaPrecoField;
        
        private string dsUnidadeField;
        
        private decimal vlValorLiquidoField;
        
        private bool vlValorLiquidoFieldSpecified;
        
        private decimal vlValorOriginalField;
        
        private bool vlValorOriginalFieldSpecified;
        
        private decimal vlValorTabelaField;
        
        private bool vlValorTabelaFieldSpecified;
        
        private decimal quantidadeField;
        
        private bool quantidadeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idNota {
            get {
                return this.idNotaField;
            }
            set {
                this.idNotaField = value;
                this.RaisePropertyChanged("idNota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idNotaSpecified {
            get {
                return this.idNotaFieldSpecified;
            }
            set {
                this.idNotaFieldSpecified = value;
                this.RaisePropertyChanged("idNotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cdCodigoItem {
            get {
                return this.cdCodigoItemField;
            }
            set {
                this.cdCodigoItemField = value;
                this.RaisePropertyChanged("cdCodigoItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int cdNumeroSequencia {
            get {
                return this.cdNumeroSequenciaField;
            }
            set {
                this.cdNumeroSequenciaField = value;
                this.RaisePropertyChanged("cdNumeroSequencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cdNumeroSequenciaSpecified {
            get {
                return this.cdNumeroSequenciaFieldSpecified;
            }
            set {
                this.cdNumeroSequenciaFieldSpecified = value;
                this.RaisePropertyChanged("cdNumeroSequenciaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string codTabelaPreco {
            get {
                return this.codTabelaPrecoField;
            }
            set {
                this.codTabelaPrecoField = value;
                this.RaisePropertyChanged("codTabelaPreco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string dsUnidade {
            get {
                return this.dsUnidadeField;
            }
            set {
                this.dsUnidadeField = value;
                this.RaisePropertyChanged("dsUnidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal vlValorLiquido {
            get {
                return this.vlValorLiquidoField;
            }
            set {
                this.vlValorLiquidoField = value;
                this.RaisePropertyChanged("vlValorLiquido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vlValorLiquidoSpecified {
            get {
                return this.vlValorLiquidoFieldSpecified;
            }
            set {
                this.vlValorLiquidoFieldSpecified = value;
                this.RaisePropertyChanged("vlValorLiquidoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal vlValorOriginal {
            get {
                return this.vlValorOriginalField;
            }
            set {
                this.vlValorOriginalField = value;
                this.RaisePropertyChanged("vlValorOriginal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vlValorOriginalSpecified {
            get {
                return this.vlValorOriginalFieldSpecified;
            }
            set {
                this.vlValorOriginalFieldSpecified = value;
                this.RaisePropertyChanged("vlValorOriginalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public decimal vlValorTabela {
            get {
                return this.vlValorTabelaField;
            }
            set {
                this.vlValorTabelaField = value;
                this.RaisePropertyChanged("vlValorTabela");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vlValorTabelaSpecified {
            get {
                return this.vlValorTabelaFieldSpecified;
            }
            set {
                this.vlValorTabelaFieldSpecified = value;
                this.RaisePropertyChanged("vlValorTabelaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
                this.RaisePropertyChanged("quantidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantidadeSpecified {
            get {
                return this.quantidadeFieldSpecified;
            }
            set {
                this.quantidadeFieldSpecified = value;
                this.RaisePropertyChanged("quantidadeSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.integraCir2k.gjc.com.br/")]
    public partial class representanteVO : abstractVO {
        
        private int idNotaField;
        
        private bool idNotaFieldSpecified;
        
        private int cdClassificadorField;
        
        private bool cdClassificadorFieldSpecified;
        
        private string cdCodigoRepresentanteField;
        
        private int dsSequenciaField;
        
        private bool dsSequenciaFieldSpecified;
        
        private decimal pcComissaoField;
        
        private bool pcComissaoFieldSpecified;
        
        private decimal vlComissaoField;
        
        private bool vlComissaoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idNota {
            get {
                return this.idNotaField;
            }
            set {
                this.idNotaField = value;
                this.RaisePropertyChanged("idNota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idNotaSpecified {
            get {
                return this.idNotaFieldSpecified;
            }
            set {
                this.idNotaFieldSpecified = value;
                this.RaisePropertyChanged("idNotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cdClassificador {
            get {
                return this.cdClassificadorField;
            }
            set {
                this.cdClassificadorField = value;
                this.RaisePropertyChanged("cdClassificador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cdClassificadorSpecified {
            get {
                return this.cdClassificadorFieldSpecified;
            }
            set {
                this.cdClassificadorFieldSpecified = value;
                this.RaisePropertyChanged("cdClassificadorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cdCodigoRepresentante {
            get {
                return this.cdCodigoRepresentanteField;
            }
            set {
                this.cdCodigoRepresentanteField = value;
                this.RaisePropertyChanged("cdCodigoRepresentante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int dsSequencia {
            get {
                return this.dsSequenciaField;
            }
            set {
                this.dsSequenciaField = value;
                this.RaisePropertyChanged("dsSequencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dsSequenciaSpecified {
            get {
                return this.dsSequenciaFieldSpecified;
            }
            set {
                this.dsSequenciaFieldSpecified = value;
                this.RaisePropertyChanged("dsSequenciaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal pcComissao {
            get {
                return this.pcComissaoField;
            }
            set {
                this.pcComissaoField = value;
                this.RaisePropertyChanged("pcComissao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pcComissaoSpecified {
            get {
                return this.pcComissaoFieldSpecified;
            }
            set {
                this.pcComissaoFieldSpecified = value;
                this.RaisePropertyChanged("pcComissaoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal vlComissao {
            get {
                return this.vlComissaoField;
            }
            set {
                this.vlComissaoField = value;
                this.RaisePropertyChanged("vlComissao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vlComissaoSpecified {
            get {
                return this.vlComissaoFieldSpecified;
            }
            set {
                this.vlComissaoFieldSpecified = value;
                this.RaisePropertyChanged("vlComissaoSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.integraCir2k.gjc.com.br/")]
    public partial class cabecalhoNotaVO : abstractVO {
        
        private int idNotaField;
        
        private bool idNotaFieldSpecified;
        
        private string cdCNPJClienteField;
        
        private string cdCNPJTransportadorField;
        
        private string cdCodigoEstabelecimentoField;
        
        private string cdCodigoUsuarioField;
        
        private int clTipoNotaFiscalField;
        
        private bool clTipoNotaFiscalFieldSpecified;
        
        private int clTipoVendaField;
        
        private bool clTipoVendaFieldSpecified;
        
        private string dsSerieField;
        
        private string nrNotaOrigField;
        
        private System.DateTime dtEdicaoField;
        
        private bool dtEdicaoFieldSpecified;
        
        private int clDestinoTiragemField;
        
        private bool clDestinoTiragemFieldSpecified;
        
        private representanteVO representanteField;
        
        private itemNotaVO[] itemNotaField;
        
        private duplicataNotaVO[] duplicataNotaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idNota {
            get {
                return this.idNotaField;
            }
            set {
                this.idNotaField = value;
                this.RaisePropertyChanged("idNota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idNotaSpecified {
            get {
                return this.idNotaFieldSpecified;
            }
            set {
                this.idNotaFieldSpecified = value;
                this.RaisePropertyChanged("idNotaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cdCNPJCliente {
            get {
                return this.cdCNPJClienteField;
            }
            set {
                this.cdCNPJClienteField = value;
                this.RaisePropertyChanged("cdCNPJCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cdCNPJTransportador {
            get {
                return this.cdCNPJTransportadorField;
            }
            set {
                this.cdCNPJTransportadorField = value;
                this.RaisePropertyChanged("cdCNPJTransportador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string cdCodigoEstabelecimento {
            get {
                return this.cdCodigoEstabelecimentoField;
            }
            set {
                this.cdCodigoEstabelecimentoField = value;
                this.RaisePropertyChanged("cdCodigoEstabelecimento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cdCodigoUsuario {
            get {
                return this.cdCodigoUsuarioField;
            }
            set {
                this.cdCodigoUsuarioField = value;
                this.RaisePropertyChanged("cdCodigoUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int clTipoNotaFiscal {
            get {
                return this.clTipoNotaFiscalField;
            }
            set {
                this.clTipoNotaFiscalField = value;
                this.RaisePropertyChanged("clTipoNotaFiscal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clTipoNotaFiscalSpecified {
            get {
                return this.clTipoNotaFiscalFieldSpecified;
            }
            set {
                this.clTipoNotaFiscalFieldSpecified = value;
                this.RaisePropertyChanged("clTipoNotaFiscalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int clTipoVenda {
            get {
                return this.clTipoVendaField;
            }
            set {
                this.clTipoVendaField = value;
                this.RaisePropertyChanged("clTipoVenda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clTipoVendaSpecified {
            get {
                return this.clTipoVendaFieldSpecified;
            }
            set {
                this.clTipoVendaFieldSpecified = value;
                this.RaisePropertyChanged("clTipoVendaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string dsSerie {
            get {
                return this.dsSerieField;
            }
            set {
                this.dsSerieField = value;
                this.RaisePropertyChanged("dsSerie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nrNotaOrig {
            get {
                return this.nrNotaOrigField;
            }
            set {
                this.nrNotaOrigField = value;
                this.RaisePropertyChanged("nrNotaOrig");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public System.DateTime dtEdicao {
            get {
                return this.dtEdicaoField;
            }
            set {
                this.dtEdicaoField = value;
                this.RaisePropertyChanged("dtEdicao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtEdicaoSpecified {
            get {
                return this.dtEdicaoFieldSpecified;
            }
            set {
                this.dtEdicaoFieldSpecified = value;
                this.RaisePropertyChanged("dtEdicaoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int clDestinoTiragem {
            get {
                return this.clDestinoTiragemField;
            }
            set {
                this.clDestinoTiragemField = value;
                this.RaisePropertyChanged("clDestinoTiragem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clDestinoTiragemSpecified {
            get {
                return this.clDestinoTiragemFieldSpecified;
            }
            set {
                this.clDestinoTiragemFieldSpecified = value;
                this.RaisePropertyChanged("clDestinoTiragemSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public representanteVO representante {
            get {
                return this.representanteField;
            }
            set {
                this.representanteField = value;
                this.RaisePropertyChanged("representante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("itemNota", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public itemNotaVO[] itemNota {
            get {
                return this.itemNotaField;
            }
            set {
                this.itemNotaField = value;
                this.RaisePropertyChanged("itemNota");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("duplicataNota", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public duplicataNotaVO[] duplicataNota {
            get {
                return this.duplicataNotaField;
            }
            set {
                this.duplicataNotaField = value;
                this.RaisePropertyChanged("duplicataNota");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.integraCir2k.gjc.com.br/", ConfigurationName="WSGO_VA.NotaFiscalServiceBean")]
    public interface NotaFiscalServiceBean {
        
        // CODEGEN: Parameter 'mensagemVOList' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CWA.Services.WSGO_VA.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractVO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="mensagemVOList")]
        CWA.Services.WSGO_VA.gerarNotaResponse gerarNota(CWA.Services.WSGO_VA.gerarNota request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CWA.Services.WSGO_VA.gerarNotaResponse> gerarNotaAsync(CWA.Services.WSGO_VA.gerarNota request);
        
        // CODEGEN: Parameter 'mensagem' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CWA.Services.WSGO_VA.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractVO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="mensagem")]
        CWA.Services.WSGO_VA.retornarValidacaoNotaResponse retornarValidacaoNota(CWA.Services.WSGO_VA.retornarValidacaoNota request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CWA.Services.WSGO_VA.retornarValidacaoNotaResponse> retornarValidacaoNotaAsync(CWA.Services.WSGO_VA.retornarValidacaoNota request);
        
        // CODEGEN: Parameter 'mensagem' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CWA.Services.WSGO_VA.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractVO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="mensagem")]
        CWA.Services.WSGO_VA.baixarTituloResponse baixarTitulo(CWA.Services.WSGO_VA.baixarTitulo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CWA.Services.WSGO_VA.baixarTituloResponse> baixarTituloAsync(CWA.Services.WSGO_VA.baixarTitulo request);
        
        // CODEGEN: Parameter 'mensagem' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CWA.Services.WSGO_VA.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(abstractVO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="mensagem")]
        CWA.Services.WSGO_VA.retornarNotasCirResponse retornarNotasCir(CWA.Services.WSGO_VA.retornarNotasCir request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CWA.Services.WSGO_VA.retornarNotasCirResponse> retornarNotasCirAsync(CWA.Services.WSGO_VA.retornarNotasCir request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gerarNota", WrapperNamespace="http://service.integraCir2k.gjc.com.br/", IsWrapped=true)]
    public partial class gerarNota {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.integraCir2k.gjc.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("cabecalhoNotaVOList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CWA.Services.WSGO_VA.cabecalhoNotaVO[] cabecalhoNotaVOList;
        
        public gerarNota() {
        }
        
        public gerarNota(CWA.Services.WSGO_VA.cabecalhoNotaVO[] cabecalhoNotaVOList) {
            this.cabecalhoNotaVOList = cabecalhoNotaVOList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gerarNotaResponse", WrapperNamespace="http://service.integraCir2k.gjc.com.br/", IsWrapped=true)]
    public partial class gerarNotaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.integraCir2k.gjc.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("mensagemVOList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CWA.Services.WSGO_VA.mensagemVO[] mensagemVOList;
        
        public gerarNotaResponse() {
        }
        
        public gerarNotaResponse(CWA.Services.WSGO_VA.mensagemVO[] mensagemVOList) {
            this.mensagemVOList = mensagemVOList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornarValidacaoNota", WrapperNamespace="http://service.integraCir2k.gjc.com.br/", IsWrapped=true)]
    public partial class retornarValidacaoNota {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.integraCir2k.gjc.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CWA.Services.WSGO_VA.mensagemVO xmlMensagemVO;
        
        public retornarValidacaoNota() {
        }
        
        public retornarValidacaoNota(CWA.Services.WSGO_VA.mensagemVO xmlMensagemVO) {
            this.xmlMensagemVO = xmlMensagemVO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornarValidacaoNotaResponse", WrapperNamespace="http://service.integraCir2k.gjc.com.br/", IsWrapped=true)]
    public partial class retornarValidacaoNotaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.integraCir2k.gjc.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CWA.Services.WSGO_VA.mensagemVO mensagem;
        
        public retornarValidacaoNotaResponse() {
        }
        
        public retornarValidacaoNotaResponse(CWA.Services.WSGO_VA.mensagemVO mensagem) {
            this.mensagem = mensagem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="baixarTitulo", WrapperNamespace="http://service.integraCir2k.gjc.com.br/", IsWrapped=true)]
    public partial class baixarTitulo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.integraCir2k.gjc.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CWA.Services.WSGO_VA.mensagemVO xmlMensagemVO;
        
        public baixarTitulo() {
        }
        
        public baixarTitulo(CWA.Services.WSGO_VA.mensagemVO xmlMensagemVO) {
            this.xmlMensagemVO = xmlMensagemVO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="baixarTituloResponse", WrapperNamespace="http://service.integraCir2k.gjc.com.br/", IsWrapped=true)]
    public partial class baixarTituloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.integraCir2k.gjc.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CWA.Services.WSGO_VA.mensagemVO mensagem;
        
        public baixarTituloResponse() {
        }
        
        public baixarTituloResponse(CWA.Services.WSGO_VA.mensagemVO mensagem) {
            this.mensagem = mensagem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornarNotasCir", WrapperNamespace="http://service.integraCir2k.gjc.com.br/", IsWrapped=true)]
    public partial class retornarNotasCir {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.integraCir2k.gjc.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CWA.Services.WSGO_VA.mensagemListVO xmlMensagemString;
        
        public retornarNotasCir() {
        }
        
        public retornarNotasCir(CWA.Services.WSGO_VA.mensagemListVO xmlMensagemString) {
            this.xmlMensagemString = xmlMensagemString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornarNotasCirResponse", WrapperNamespace="http://service.integraCir2k.gjc.com.br/", IsWrapped=true)]
    public partial class retornarNotasCirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.integraCir2k.gjc.com.br/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CWA.Services.WSGO_VA.mensagemListVO mensagem;
        
        public retornarNotasCirResponse() {
        }
        
        public retornarNotasCirResponse(CWA.Services.WSGO_VA.mensagemListVO mensagem) {
            this.mensagem = mensagem;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NotaFiscalServiceBeanChannel : CWA.Services.WSGO_VA.NotaFiscalServiceBean, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotaFiscalServiceBeanClient : System.ServiceModel.ClientBase<CWA.Services.WSGO_VA.NotaFiscalServiceBean>, CWA.Services.WSGO_VA.NotaFiscalServiceBean {
        
        public NotaFiscalServiceBeanClient() {
        }
        
        public NotaFiscalServiceBeanClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotaFiscalServiceBeanClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotaFiscalServiceBeanClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotaFiscalServiceBeanClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CWA.Services.WSGO_VA.gerarNotaResponse CWA.Services.WSGO_VA.NotaFiscalServiceBean.gerarNota(CWA.Services.WSGO_VA.gerarNota request) {
            return base.Channel.gerarNota(request);
        }
        
        public CWA.Services.WSGO_VA.mensagemVO[] gerarNota(CWA.Services.WSGO_VA.cabecalhoNotaVO[] cabecalhoNotaVOList) {
            CWA.Services.WSGO_VA.gerarNota inValue = new CWA.Services.WSGO_VA.gerarNota();
            inValue.cabecalhoNotaVOList = cabecalhoNotaVOList;
            CWA.Services.WSGO_VA.gerarNotaResponse retVal = ((CWA.Services.WSGO_VA.NotaFiscalServiceBean)(this)).gerarNota(inValue);
            return retVal.mensagemVOList;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CWA.Services.WSGO_VA.gerarNotaResponse> CWA.Services.WSGO_VA.NotaFiscalServiceBean.gerarNotaAsync(CWA.Services.WSGO_VA.gerarNota request) {
            return base.Channel.gerarNotaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CWA.Services.WSGO_VA.gerarNotaResponse> gerarNotaAsync(CWA.Services.WSGO_VA.cabecalhoNotaVO[] cabecalhoNotaVOList) {
            CWA.Services.WSGO_VA.gerarNota inValue = new CWA.Services.WSGO_VA.gerarNota();
            inValue.cabecalhoNotaVOList = cabecalhoNotaVOList;
            return ((CWA.Services.WSGO_VA.NotaFiscalServiceBean)(this)).gerarNotaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CWA.Services.WSGO_VA.retornarValidacaoNotaResponse CWA.Services.WSGO_VA.NotaFiscalServiceBean.retornarValidacaoNota(CWA.Services.WSGO_VA.retornarValidacaoNota request) {
            return base.Channel.retornarValidacaoNota(request);
        }
        
        public CWA.Services.WSGO_VA.mensagemVO retornarValidacaoNota(CWA.Services.WSGO_VA.mensagemVO xmlMensagemVO) {
            CWA.Services.WSGO_VA.retornarValidacaoNota inValue = new CWA.Services.WSGO_VA.retornarValidacaoNota();
            inValue.xmlMensagemVO = xmlMensagemVO;
            CWA.Services.WSGO_VA.retornarValidacaoNotaResponse retVal = ((CWA.Services.WSGO_VA.NotaFiscalServiceBean)(this)).retornarValidacaoNota(inValue);
            return retVal.mensagem;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CWA.Services.WSGO_VA.retornarValidacaoNotaResponse> CWA.Services.WSGO_VA.NotaFiscalServiceBean.retornarValidacaoNotaAsync(CWA.Services.WSGO_VA.retornarValidacaoNota request) {
            return base.Channel.retornarValidacaoNotaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CWA.Services.WSGO_VA.retornarValidacaoNotaResponse> retornarValidacaoNotaAsync(CWA.Services.WSGO_VA.mensagemVO xmlMensagemVO) {
            CWA.Services.WSGO_VA.retornarValidacaoNota inValue = new CWA.Services.WSGO_VA.retornarValidacaoNota();
            inValue.xmlMensagemVO = xmlMensagemVO;
            return ((CWA.Services.WSGO_VA.NotaFiscalServiceBean)(this)).retornarValidacaoNotaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CWA.Services.WSGO_VA.baixarTituloResponse CWA.Services.WSGO_VA.NotaFiscalServiceBean.baixarTitulo(CWA.Services.WSGO_VA.baixarTitulo request) {
            return base.Channel.baixarTitulo(request);
        }
        
        public CWA.Services.WSGO_VA.mensagemVO baixarTitulo(CWA.Services.WSGO_VA.mensagemVO xmlMensagemVO) {
            CWA.Services.WSGO_VA.baixarTitulo inValue = new CWA.Services.WSGO_VA.baixarTitulo();
            inValue.xmlMensagemVO = xmlMensagemVO;
            CWA.Services.WSGO_VA.baixarTituloResponse retVal = ((CWA.Services.WSGO_VA.NotaFiscalServiceBean)(this)).baixarTitulo(inValue);
            return retVal.mensagem;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CWA.Services.WSGO_VA.baixarTituloResponse> CWA.Services.WSGO_VA.NotaFiscalServiceBean.baixarTituloAsync(CWA.Services.WSGO_VA.baixarTitulo request) {
            return base.Channel.baixarTituloAsync(request);
        }
        
        public System.Threading.Tasks.Task<CWA.Services.WSGO_VA.baixarTituloResponse> baixarTituloAsync(CWA.Services.WSGO_VA.mensagemVO xmlMensagemVO) {
            CWA.Services.WSGO_VA.baixarTitulo inValue = new CWA.Services.WSGO_VA.baixarTitulo();
            inValue.xmlMensagemVO = xmlMensagemVO;
            return ((CWA.Services.WSGO_VA.NotaFiscalServiceBean)(this)).baixarTituloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CWA.Services.WSGO_VA.retornarNotasCirResponse CWA.Services.WSGO_VA.NotaFiscalServiceBean.retornarNotasCir(CWA.Services.WSGO_VA.retornarNotasCir request) {
            return base.Channel.retornarNotasCir(request);
        }
        
        public CWA.Services.WSGO_VA.mensagemListVO retornarNotasCir(CWA.Services.WSGO_VA.mensagemListVO xmlMensagemString) {
            CWA.Services.WSGO_VA.retornarNotasCir inValue = new CWA.Services.WSGO_VA.retornarNotasCir();
            inValue.xmlMensagemString = xmlMensagemString;
            CWA.Services.WSGO_VA.retornarNotasCirResponse retVal = ((CWA.Services.WSGO_VA.NotaFiscalServiceBean)(this)).retornarNotasCir(inValue);
            return retVal.mensagem;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CWA.Services.WSGO_VA.retornarNotasCirResponse> CWA.Services.WSGO_VA.NotaFiscalServiceBean.retornarNotasCirAsync(CWA.Services.WSGO_VA.retornarNotasCir request) {
            return base.Channel.retornarNotasCirAsync(request);
        }
        
        public System.Threading.Tasks.Task<CWA.Services.WSGO_VA.retornarNotasCirResponse> retornarNotasCirAsync(CWA.Services.WSGO_VA.mensagemListVO xmlMensagemString) {
            CWA.Services.WSGO_VA.retornarNotasCir inValue = new CWA.Services.WSGO_VA.retornarNotasCir();
            inValue.xmlMensagemString = xmlMensagemString;
            return ((CWA.Services.WSGO_VA.NotaFiscalServiceBean)(this)).retornarNotasCirAsync(inValue);
        }
    }
}
