//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWA.Util.CWAMailAPIService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CWAMailAPIService.IServiceCWA")]
    public interface IServiceCWA {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/BRASPAG_VendaSimplesCartao", ReplyAction="http://tempuri.org/IServiceCWA/BRASPAG_VendaSimplesCartaoResponse")]
        string[] BRASPAG_VendaSimplesCartao(
                    string pstrUrlPost, 
                    string pstrContentType, 
                    string pstrMethod, 
                    string pstrMerchantID, 
                    string pstrMerchantKey, 
                    string pstrRequestId, 
                    string pstrProviderPagamento, 
                    string pstrNomeComprador, 
                    string pstrValor, 
                    string pstrParcela, 
                    string pstrCartao, 
                    string pstrNomeCompradorImpressoCartao, 
                    string pstrValidade, 
                    string pstrCVV, 
                    string pstrBandeira, 
                    string pstrIdentificadorVenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/BRASPAG_VendaSimplesCartao", ReplyAction="http://tempuri.org/IServiceCWA/BRASPAG_VendaSimplesCartaoResponse")]
        System.Threading.Tasks.Task<string[]> BRASPAG_VendaSimplesCartaoAsync(
                    string pstrUrlPost, 
                    string pstrContentType, 
                    string pstrMethod, 
                    string pstrMerchantID, 
                    string pstrMerchantKey, 
                    string pstrRequestId, 
                    string pstrProviderPagamento, 
                    string pstrNomeComprador, 
                    string pstrValor, 
                    string pstrParcela, 
                    string pstrCartao, 
                    string pstrNomeCompradorImpressoCartao, 
                    string pstrValidade, 
                    string pstrCVV, 
                    string pstrBandeira, 
                    string pstrIdentificadorVenda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetStatusContrato", ReplyAction="http://tempuri.org/IServiceCWA/GetStatusContratoResponse")]
        string[] GetStatusContrato(string pstrCodAssinante, string pstrCodContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetStatusContrato", ReplyAction="http://tempuri.org/IServiceCWA/GetStatusContratoResponse")]
        System.Threading.Tasks.Task<string[]> GetStatusContratoAsync(string pstrCodAssinante, string pstrCodContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetStatusContratoJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetStatusContratoJSONResponse")]
        string GetStatusContratoJSON(string pstrCodAssinante, string pstrCodContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetStatusContratoJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetStatusContratoJSONResponse")]
        System.Threading.Tasks.Task<string> GetStatusContratoJSONAsync(string pstrCodAssinante, string pstrCodContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetLoginValidoMirante", ReplyAction="http://tempuri.org/IServiceCWA/GetLoginValidoMiranteResponse")]
        string[] GetLoginValidoMirante(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetLoginValidoMirante", ReplyAction="http://tempuri.org/IServiceCWA/GetLoginValidoMiranteResponse")]
        System.Threading.Tasks.Task<string[]> GetLoginValidoMiranteAsync(string Token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCarteiraClubeMiranteJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetCarteiraClubeMiranteJSONResponse")]
        string GetCarteiraClubeMiranteJSON(string pstrCodAssinante, string pstrCodContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCarteiraClubeMiranteJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetCarteiraClubeMiranteJSONResponse")]
        System.Threading.Tasks.Task<string> GetCarteiraClubeMiranteJSONAsync(string pstrCodAssinante, string pstrCodContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCarteiraClubeMirante", ReplyAction="http://tempuri.org/IServiceCWA/GetCarteiraClubeMiranteResponse")]
        CWA.Venda.Entity.ClubeAssinanteEntity GetCarteiraClubeMirante(string pstrCodAssinante, string pstrCodContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCarteiraClubeMirante", ReplyAction="http://tempuri.org/IServiceCWA/GetCarteiraClubeMiranteResponse")]
        System.Threading.Tasks.Task<CWA.Venda.Entity.ClubeAssinanteEntity> GetCarteiraClubeMiranteAsync(string pstrCodAssinante, string pstrCodContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/ConsomeWebServiceDinamico", ReplyAction="http://tempuri.org/IServiceCWA/ConsomeWebServiceDinamicoResponse")]
        string ConsomeWebServiceDinamico(string pstrSoapSTR, string pstrFormatParametro, string pstrUrlWSclient, string pstrMetodoNomeWSClient, string pstrUriSoap, string pstrContentType, string pstrAccept, string pstrMethod, System.Collections.Generic.Dictionary<string, string> pdicParametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/ConsomeWebServiceDinamico", ReplyAction="http://tempuri.org/IServiceCWA/ConsomeWebServiceDinamicoResponse")]
        System.Threading.Tasks.Task<string> ConsomeWebServiceDinamicoAsync(string pstrSoapSTR, string pstrFormatParametro, string pstrUrlWSclient, string pstrMetodoNomeWSClient, string pstrUriSoap, string pstrContentType, string pstrAccept, string pstrMethod, System.Collections.Generic.Dictionary<string, string> pdicParametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/ConsomeApiQualityGoiania", ReplyAction="http://tempuri.org/IServiceCWA/ConsomeApiQualityGoianiaResponse")]
        string ConsomeApiQualityGoiania(string ptrsURL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/ConsomeApiQualityGoiania", ReplyAction="http://tempuri.org/IServiceCWA/ConsomeApiQualityGoianiaResponse")]
        System.Threading.Tasks.Task<string> ConsomeApiQualityGoianiaAsync(string ptrsURL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetVersaoWS", ReplyAction="http://tempuri.org/IServiceCWA/GetVersaoWSResponse")]
        string GetVersaoWS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetVersaoWS", ReplyAction="http://tempuri.org/IServiceCWA/GetVersaoWSResponse")]
        System.Threading.Tasks.Task<string> GetVersaoWSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/BRASPAG_GetVendaMerchantOrderId", ReplyAction="http://tempuri.org/IServiceCWA/BRASPAG_GetVendaMerchantOrderIdResponse")]
        string[] BRASPAG_GetVendaMerchantOrderId(string pstrUrlPost, string pstrContentType, string pstrMethod, string pstrMerchantID, string pstrMerchantKey, string pstrRequestId, string pstrMerchantOrderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/BRASPAG_GetVendaMerchantOrderId", ReplyAction="http://tempuri.org/IServiceCWA/BRASPAG_GetVendaMerchantOrderIdResponse")]
        System.Threading.Tasks.Task<string[]> BRASPAG_GetVendaMerchantOrderIdAsync(string pstrUrlPost, string pstrContentType, string pstrMethod, string pstrMerchantID, string pstrMerchantKey, string pstrRequestId, string pstrMerchantOrderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/BRASPAG_GetVendaPaymentId", ReplyAction="http://tempuri.org/IServiceCWA/BRASPAG_GetVendaPaymentIdResponse")]
        string[] BRASPAG_GetVendaPaymentId(string pstrUrlPost, string pstrContentType, string pstrMethod, string pstrMerchantID, string pstrMerchantKey, string pstrRequestId, string pstrPaymentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/BRASPAG_GetVendaPaymentId", ReplyAction="http://tempuri.org/IServiceCWA/BRASPAG_GetVendaPaymentIdResponse")]
        System.Threading.Tasks.Task<string[]> BRASPAG_GetVendaPaymentIdAsync(string pstrUrlPost, string pstrContentType, string pstrMethod, string pstrMerchantID, string pstrMerchantKey, string pstrRequestId, string pstrPaymentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/SetGeraNotaVA_GO", ReplyAction="http://tempuri.org/IServiceCWA/SetGeraNotaVA_GOResponse")]
        string SetGeraNotaVA_GO(string pstrTipoEndPointClient, string pstrEndPointClient, string pstrBanco, string pstrServidor, string pstrUsuario, string pstrDataInicio, string pstrDataFim, string pstrPathLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/SetGeraNotaVA_GO", ReplyAction="http://tempuri.org/IServiceCWA/SetGeraNotaVA_GOResponse")]
        System.Threading.Tasks.Task<string> SetGeraNotaVA_GOAsync(string pstrTipoEndPointClient, string pstrEndPointClient, string pstrBanco, string pstrServidor, string pstrUsuario, string pstrDataInicio, string pstrDataFim, string pstrPathLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetDadosContratoJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetDadosContratoJSONResponse")]
        string GetDadosContratoJSON(string pstrCodAssinante, string pstrCodContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetDadosContratoJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetDadosContratoJSONResponse")]
        System.Threading.Tasks.Task<string> GetDadosContratoJSONAsync(string pstrCodAssinante, string pstrCodContrato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetRamoAtividadeJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetRamoAtividadeJSONResponse")]
        string GetRamoAtividadeJSON(int pintTipo, int pintSituacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetRamoAtividadeJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetRamoAtividadeJSONResponse")]
        System.Threading.Tasks.Task<string> GetRamoAtividadeJSONAsync(int pintTipo, int pintSituacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetRamoAtividade", ReplyAction="http://tempuri.org/IServiceCWA/GetRamoAtividadeResponse")]
        CWA.Venda.Entity.RamoAtividadeEntity[] GetRamoAtividade(int pintTipo, int pintSituacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetRamoAtividade", ReplyAction="http://tempuri.org/IServiceCWA/GetRamoAtividadeResponse")]
        System.Threading.Tasks.Task<CWA.Venda.Entity.RamoAtividadeEntity[]> GetRamoAtividadeAsync(int pintTipo, int pintSituacao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboClientejcJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboClientejcJSONResponse")]
        string GetCuboClientejcJSON();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboClientejcJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboClientejcJSONResponse")]
        System.Threading.Tasks.Task<string> GetCuboClientejcJSONAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboClientejc", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboClientejcResponse")]
        CWA.Venda.Entity.CuboClienteJCEntity[] GetCuboClientejc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboClientejc", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboClientejcResponse")]
        System.Threading.Tasks.Task<CWA.Venda.Entity.CuboClienteJCEntity[]> GetCuboClientejcAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboAssinaturajcJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboAssinaturajcJSONResponse")]
        string GetCuboAssinaturajcJSON(string psDtInicioInic, string psDtInicioFim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboAssinaturajcJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboAssinaturajcJSONResponse")]
        System.Threading.Tasks.Task<string> GetCuboAssinaturajcJSONAsync(string psDtInicioInic, string psDtInicioFim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboAssinaturajc", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboAssinaturajcResponse")]
        CWA.Venda.Entity.CuboAssinaturaJCEntity[] GetCuboAssinaturajc(string psDtInicioInic, string psDtInicioFim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboAssinaturajc", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboAssinaturajcResponse")]
        System.Threading.Tasks.Task<CWA.Venda.Entity.CuboAssinaturaJCEntity[]> GetCuboAssinaturajcAsync(string psDtInicioInic, string psDtInicioFim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboRecibojcJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboRecibojcJSONResponse")]
        string GetCuboRecibojcJSON(string psDtInicioInic, string psDtInicioFim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboRecibojcJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboRecibojcJSONResponse")]
        System.Threading.Tasks.Task<string> GetCuboRecibojcJSONAsync(string psDtInicioInic, string psDtInicioFim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboRecibojc", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboRecibojcResponse")]
        CWA.Venda.Entity.CuboReciboJCEntity[] GetCuboRecibojc(string psDtInicioInic, string psDtInicioFim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboRecibojc", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboRecibojcResponse")]
        System.Threading.Tasks.Task<CWA.Venda.Entity.CuboReciboJCEntity[]> GetCuboRecibojcAsync(string psDtInicioInic, string psDtInicioFim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboProdutojcJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboProdutojcJSONResponse")]
        string GetCuboProdutojcJSON();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboProdutojcJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboProdutojcJSONResponse")]
        System.Threading.Tasks.Task<string> GetCuboProdutojcJSONAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboProdutojc", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboProdutojcResponse")]
        CWA.Venda.Entity.CuboProdutoJCEntity[] GetCuboProdutojc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboProdutojc", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboProdutojcResponse")]
        System.Threading.Tasks.Task<CWA.Venda.Entity.CuboProdutoJCEntity[]> GetCuboProdutojcAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboProdAgregjcJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboProdAgregjcJSONResponse")]
        string GetCuboProdAgregjcJSON();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboProdAgregjcJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboProdAgregjcJSONResponse")]
        System.Threading.Tasks.Task<string> GetCuboProdAgregjcJSONAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboProdAgregjc", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboProdAgregjcResponse")]
        CWA.Venda.Entity.CuboProdAgregJCEntity[] GetCuboProdAgregjc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboProdAgregjc", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboProdAgregjcResponse")]
        System.Threading.Tasks.Task<CWA.Venda.Entity.CuboProdAgregJCEntity[]> GetCuboProdAgregjcAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboTipoRecJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboTipoRecJSONResponse")]
        string GetCuboTipoRecJSON();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboTipoRecJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboTipoRecJSONResponse")]
        System.Threading.Tasks.Task<string> GetCuboTipoRecJSONAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboTiposRecjc", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboTiposRecjcResponse")]
        CWA.Venda.Entity.CuboTiposRecJCEntity[] GetCuboTiposRecjc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboTiposRecjc", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboTiposRecjcResponse")]
        System.Threading.Tasks.Task<CWA.Venda.Entity.CuboTiposRecJCEntity[]> GetCuboTiposRecjcAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboMovRecJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboMovRecJSONResponse")]
        string GetCuboMovRecJSON(string psDtInicioInic, string psDtInicioFim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboMovRecJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboMovRecJSONResponse")]
        System.Threading.Tasks.Task<string> GetCuboMovRecJSONAsync(string psDtInicioInic, string psDtInicioFim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboMovRecjc", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboMovRecjcResponse")]
        CWA.Venda.Entity.CuboMovRecJCEntity[] GetCuboMovRecjc(string psDtInicioInic, string psDtInicioFim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCuboMovRecjc", ReplyAction="http://tempuri.org/IServiceCWA/GetCuboMovRecjcResponse")]
        System.Threading.Tasks.Task<CWA.Venda.Entity.CuboMovRecJCEntity[]> GetCuboMovRecjcAsync(string psDtInicioInic, string psDtInicioFim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetConteudoDestaque", ReplyAction="http://tempuri.org/IServiceCWA/GetConteudoDestaqueResponse")]
        string GetConteudoDestaque(string pstrPathConteudo, string pstrPathImgMKT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetConteudoDestaque", ReplyAction="http://tempuri.org/IServiceCWA/GetConteudoDestaqueResponse")]
        System.Threading.Tasks.Task<string> GetConteudoDestaqueAsync(string pstrPathConteudo, string pstrPathImgMKT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetConteudoPromocao", ReplyAction="http://tempuri.org/IServiceCWA/GetConteudoPromocaoResponse")]
        string GetConteudoPromocao(string pstrPathConteudo, string pstrPathImgMKT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetConteudoPromocao", ReplyAction="http://tempuri.org/IServiceCWA/GetConteudoPromocaoResponse")]
        System.Threading.Tasks.Task<string> GetConteudoPromocaoAsync(string pstrPathConteudo, string pstrPathImgMKT);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetConteudoDetalhe", ReplyAction="http://tempuri.org/IServiceCWA/GetConteudoDetalheResponse")]
        string GetConteudoDetalhe(string pstrPathConteudo, string pstrPathImgMKT, int pintIDCampanha, int pintIDPlano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetConteudoDetalhe", ReplyAction="http://tempuri.org/IServiceCWA/GetConteudoDetalheResponse")]
        System.Threading.Tasks.Task<string> GetConteudoDetalheAsync(string pstrPathConteudo, string pstrPathImgMKT, int pintIDCampanha, int pintIDPlano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetMontarBannerDestaque", ReplyAction="http://tempuri.org/IServiceCWA/GetMontarBannerDestaqueResponse")]
        string GetMontarBannerDestaque();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetMontarBannerDestaque", ReplyAction="http://tempuri.org/IServiceCWA/GetMontarBannerDestaqueResponse")]
        System.Threading.Tasks.Task<string> GetMontarBannerDestaqueAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetRamoAtividadeListJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetRamoAtividadeListJSONResponse")]
        string GetRamoAtividadeListJSON(int pintTipoRamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetRamoAtividadeListJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetRamoAtividadeListJSONResponse")]
        System.Threading.Tasks.Task<string> GetRamoAtividadeListJSONAsync(int pintTipoRamo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetPrecoCampanhaPlanoProdutoJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetPrecoCampanhaPlanoProdutoJSONResponse")]
        string GetPrecoCampanhaPlanoProdutoJSON(int pintIDCampaha, int pintIDPlano, int pintProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetPrecoCampanhaPlanoProdutoJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetPrecoCampanhaPlanoProdutoJSONResponse")]
        System.Threading.Tasks.Task<string> GetPrecoCampanhaPlanoProdutoJSONAsync(int pintIDCampaha, int pintIDPlano, int pintProduto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetTipoLogradouroListJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetTipoLogradouroListJSONResponse")]
        string GetTipoLogradouroListJSON();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetTipoLogradouroListJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetTipoLogradouroListJSONResponse")]
        System.Threading.Tasks.Task<string> GetTipoLogradouroListJSONAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetViewLogrEntityJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetViewLogrEntityJSONResponse")]
        string GetViewLogrEntityJSON(string pstrCEP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetViewLogrEntityJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetViewLogrEntityJSONResponse")]
        System.Threading.Tasks.Task<string> GetViewLogrEntityJSONAsync(string pstrCEP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCodRoteirizacaoJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetCodRoteirizacaoJSONResponse")]
        string GetCodRoteirizacaoJSON(int pintIDProduto, int pintIDLogr, int pintNumeroResid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetCodRoteirizacaoJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetCodRoteirizacaoJSONResponse")]
        System.Threading.Tasks.Task<string> GetCodRoteirizacaoJSONAsync(int pintIDProduto, int pintIDLogr, int pintNumeroResid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetParametroGlobalWEBJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetParametroGlobalWEBJSONResponse")]
        string GetParametroGlobalWEBJSON();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetParametroGlobalWEBJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetParametroGlobalWEBJSONResponse")]
        System.Threading.Tasks.Task<string> GetParametroGlobalWEBJSONAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetBandeiraCartaoListJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetBandeiraCartaoListJSONResponse")]
        string GetBandeiraCartaoListJSON();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetBandeiraCartaoListJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetBandeiraCartaoListJSONResponse")]
        System.Threading.Tasks.Task<string> GetBandeiraCartaoListJSONAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetAdmCartaoListJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetAdmCartaoListJSONResponse")]
        string GetAdmCartaoListJSON(int pintBandeira);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetAdmCartaoListJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetAdmCartaoListJSONResponse")]
        System.Threading.Tasks.Task<string> GetAdmCartaoListJSONAsync(int pintBandeira);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetAdmCobraGateWayJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetAdmCobraGateWayJSONResponse")]
        string GetAdmCobraGateWayJSON(int pintIDAdmCartao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetAdmCobraGateWayJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetAdmCobraGateWayJSONResponse")]
        System.Threading.Tasks.Task<string> GetAdmCobraGateWayJSONAsync(int pintIDAdmCartao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetBandeiraCartaoListNovoJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetBandeiraCartaoListNovoJSONResponse")]
        string GetBandeiraCartaoListNovoJSON();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetBandeiraCartaoListNovoJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetBandeiraCartaoListNovoJSONResponse")]
        System.Threading.Tasks.Task<string> GetBandeiraCartaoListNovoJSONAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetValidarListaNegraJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetValidarListaNegraJSONResponse")]
        string GetValidarListaNegraJSON(CWA.Venda.Entity.ListaNegraEntity pObjEnt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetValidarListaNegraJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetValidarListaNegraJSONResponse")]
        System.Threading.Tasks.Task<string> GetValidarListaNegraJSONAsync(CWA.Venda.Entity.ListaNegraEntity pObjEnt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetContabilContratoJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetContabilContratoJSONResponse")]
        string GetContabilContratoJSON(int pintCTR, int pintDVCTR, string pstrSerieCTR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetContabilContratoJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetContabilContratoJSONResponse")]
        System.Threading.Tasks.Task<string> GetContabilContratoJSONAsync(int pintCTR, int pintDVCTR, string pstrSerieCTR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetParametrosPlanoJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetParametrosPlanoJSONResponse")]
        string GetParametrosPlanoJSON(int pintIDPlano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetParametrosPlanoJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetParametrosPlanoJSONResponse")]
        System.Threading.Tasks.Task<string> GetParametrosPlanoJSONAsync(int pintIDPlano);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetTipoAssinaturaListJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetTipoAssinaturaListJSONResponse")]
        string GetTipoAssinaturaListJSON(int pintIDProduto, int pintIDCampanha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetTipoAssinaturaListJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetTipoAssinaturaListJSONResponse")]
        System.Threading.Tasks.Task<string> GetTipoAssinaturaListJSONAsync(int pintIDProduto, int pintIDCampanha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetTipoPagamentoListJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetTipoPagamentoListJSONResponse")]
        string GetTipoPagamentoListJSON(int pintIDProduto, int pintIDCampanha, int pintIDTipoAssinatura, int pintTipoEntrega);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetTipoPagamentoListJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetTipoPagamentoListJSONResponse")]
        System.Threading.Tasks.Task<string> GetTipoPagamentoListJSONAsync(int pintIDProduto, int pintIDCampanha, int pintIDTipoAssinatura, int pintTipoEntrega);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetBancoDebitoListJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetBancoDebitoListJSONResponse")]
        string GetBancoDebitoListJSON(int pintIDProdudo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetBancoDebitoListJSON", ReplyAction="http://tempuri.org/IServiceCWA/GetBancoDebitoListJSONResponse")]
        System.Threading.Tasks.Task<string> GetBancoDebitoListJSONAsync(int pintIDProdudo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GravarAssinaturaService", ReplyAction="http://tempuri.org/IServiceCWA/GravarAssinaturaServiceResponse")]
        string GravarAssinaturaService(CWA.Venda.Entity.DadosPessoaEntity ObjPS, CWA.Venda.Entity.DadosEntregaEntity ObjDE, CWA.Venda.Entity.DadosPagamentoEntity ObjPG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GravarAssinaturaService", ReplyAction="http://tempuri.org/IServiceCWA/GravarAssinaturaServiceResponse")]
        System.Threading.Tasks.Task<string> GravarAssinaturaServiceAsync(CWA.Venda.Entity.DadosPessoaEntity ObjPS, CWA.Venda.Entity.DadosEntregaEntity ObjDE, CWA.Venda.Entity.DadosPagamentoEntity ObjPG);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GravarAbandonoService", ReplyAction="http://tempuri.org/IServiceCWA/GravarAbandonoServiceResponse")]
        string GravarAbandonoService(string pstrDOC, string pstrEmail, CWA.Venda.Entity.AbandonoEntity pObjEnt, int pintEtapa, int pintStatus, string pstrNuSerieCTR, int pintNuCTR, int pintNuDvCTR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GravarAbandonoService", ReplyAction="http://tempuri.org/IServiceCWA/GravarAbandonoServiceResponse")]
        System.Threading.Tasks.Task<string> GravarAbandonoServiceAsync(string pstrDOC, string pstrEmail, CWA.Venda.Entity.AbandonoEntity pObjEnt, int pintEtapa, int pintStatus, string pstrNuSerieCTR, int pintNuCTR, int pintNuDvCTR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetAbandonoLojaService", ReplyAction="http://tempuri.org/IServiceCWA/GetAbandonoLojaServiceResponse")]
        string GetAbandonoLojaService(string pstrDOC, int pintTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/GetAbandonoLojaService", ReplyAction="http://tempuri.org/IServiceCWA/GetAbandonoLojaServiceResponse")]
        System.Threading.Tasks.Task<string> GetAbandonoLojaServiceAsync(string pstrDOC, int pintTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/SendMailAPI", ReplyAction="http://tempuri.org/IServiceCWA/SendMailAPIResponse")]
        string SendMailAPI(string pstrUrlBasePOST, string pstrAPIKey, string pstrDomain, string pstrFromMail, string pstrToMail, string pstrSubject, string pstrText, int pintTipoEmail, string pstrPathAnexo, string pstrFileAnexo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCWA/SendMailAPI", ReplyAction="http://tempuri.org/IServiceCWA/SendMailAPIResponse")]
        System.Threading.Tasks.Task<string> SendMailAPIAsync(string pstrUrlBasePOST, string pstrAPIKey, string pstrDomain, string pstrFromMail, string pstrToMail, string pstrSubject, string pstrText, int pintTipoEmail, string pstrPathAnexo, string pstrFileAnexo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCWAChannel : CWA.Util.CWAMailAPIService.IServiceCWA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCWAClient : System.ServiceModel.ClientBase<CWA.Util.CWAMailAPIService.IServiceCWA>, CWA.Util.CWAMailAPIService.IServiceCWA {
        
        public ServiceCWAClient() {
        }
        
        public ServiceCWAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCWAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCWAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCWAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] BRASPAG_VendaSimplesCartao(
                    string pstrUrlPost, 
                    string pstrContentType, 
                    string pstrMethod, 
                    string pstrMerchantID, 
                    string pstrMerchantKey, 
                    string pstrRequestId, 
                    string pstrProviderPagamento, 
                    string pstrNomeComprador, 
                    string pstrValor, 
                    string pstrParcela, 
                    string pstrCartao, 
                    string pstrNomeCompradorImpressoCartao, 
                    string pstrValidade, 
                    string pstrCVV, 
                    string pstrBandeira, 
                    string pstrIdentificadorVenda) {
            return base.Channel.BRASPAG_VendaSimplesCartao(pstrUrlPost, pstrContentType, pstrMethod, pstrMerchantID, pstrMerchantKey, pstrRequestId, pstrProviderPagamento, pstrNomeComprador, pstrValor, pstrParcela, pstrCartao, pstrNomeCompradorImpressoCartao, pstrValidade, pstrCVV, pstrBandeira, pstrIdentificadorVenda);
        }
        
        public System.Threading.Tasks.Task<string[]> BRASPAG_VendaSimplesCartaoAsync(
                    string pstrUrlPost, 
                    string pstrContentType, 
                    string pstrMethod, 
                    string pstrMerchantID, 
                    string pstrMerchantKey, 
                    string pstrRequestId, 
                    string pstrProviderPagamento, 
                    string pstrNomeComprador, 
                    string pstrValor, 
                    string pstrParcela, 
                    string pstrCartao, 
                    string pstrNomeCompradorImpressoCartao, 
                    string pstrValidade, 
                    string pstrCVV, 
                    string pstrBandeira, 
                    string pstrIdentificadorVenda) {
            return base.Channel.BRASPAG_VendaSimplesCartaoAsync(pstrUrlPost, pstrContentType, pstrMethod, pstrMerchantID, pstrMerchantKey, pstrRequestId, pstrProviderPagamento, pstrNomeComprador, pstrValor, pstrParcela, pstrCartao, pstrNomeCompradorImpressoCartao, pstrValidade, pstrCVV, pstrBandeira, pstrIdentificadorVenda);
        }
        
        public string[] GetStatusContrato(string pstrCodAssinante, string pstrCodContrato) {
            return base.Channel.GetStatusContrato(pstrCodAssinante, pstrCodContrato);
        }
        
        public System.Threading.Tasks.Task<string[]> GetStatusContratoAsync(string pstrCodAssinante, string pstrCodContrato) {
            return base.Channel.GetStatusContratoAsync(pstrCodAssinante, pstrCodContrato);
        }
        
        public string GetStatusContratoJSON(string pstrCodAssinante, string pstrCodContrato) {
            return base.Channel.GetStatusContratoJSON(pstrCodAssinante, pstrCodContrato);
        }
        
        public System.Threading.Tasks.Task<string> GetStatusContratoJSONAsync(string pstrCodAssinante, string pstrCodContrato) {
            return base.Channel.GetStatusContratoJSONAsync(pstrCodAssinante, pstrCodContrato);
        }
        
        public string[] GetLoginValidoMirante(string Token) {
            return base.Channel.GetLoginValidoMirante(Token);
        }
        
        public System.Threading.Tasks.Task<string[]> GetLoginValidoMiranteAsync(string Token) {
            return base.Channel.GetLoginValidoMiranteAsync(Token);
        }
        
        public string GetCarteiraClubeMiranteJSON(string pstrCodAssinante, string pstrCodContrato) {
            return base.Channel.GetCarteiraClubeMiranteJSON(pstrCodAssinante, pstrCodContrato);
        }
        
        public System.Threading.Tasks.Task<string> GetCarteiraClubeMiranteJSONAsync(string pstrCodAssinante, string pstrCodContrato) {
            return base.Channel.GetCarteiraClubeMiranteJSONAsync(pstrCodAssinante, pstrCodContrato);
        }
        
        public CWA.Venda.Entity.ClubeAssinanteEntity GetCarteiraClubeMirante(string pstrCodAssinante, string pstrCodContrato) {
            return base.Channel.GetCarteiraClubeMirante(pstrCodAssinante, pstrCodContrato);
        }
        
        public System.Threading.Tasks.Task<CWA.Venda.Entity.ClubeAssinanteEntity> GetCarteiraClubeMiranteAsync(string pstrCodAssinante, string pstrCodContrato) {
            return base.Channel.GetCarteiraClubeMiranteAsync(pstrCodAssinante, pstrCodContrato);
        }
        
        public string ConsomeWebServiceDinamico(string pstrSoapSTR, string pstrFormatParametro, string pstrUrlWSclient, string pstrMetodoNomeWSClient, string pstrUriSoap, string pstrContentType, string pstrAccept, string pstrMethod, System.Collections.Generic.Dictionary<string, string> pdicParametros) {
            return base.Channel.ConsomeWebServiceDinamico(pstrSoapSTR, pstrFormatParametro, pstrUrlWSclient, pstrMetodoNomeWSClient, pstrUriSoap, pstrContentType, pstrAccept, pstrMethod, pdicParametros);
        }
        
        public System.Threading.Tasks.Task<string> ConsomeWebServiceDinamicoAsync(string pstrSoapSTR, string pstrFormatParametro, string pstrUrlWSclient, string pstrMetodoNomeWSClient, string pstrUriSoap, string pstrContentType, string pstrAccept, string pstrMethod, System.Collections.Generic.Dictionary<string, string> pdicParametros) {
            return base.Channel.ConsomeWebServiceDinamicoAsync(pstrSoapSTR, pstrFormatParametro, pstrUrlWSclient, pstrMetodoNomeWSClient, pstrUriSoap, pstrContentType, pstrAccept, pstrMethod, pdicParametros);
        }
        
        public string ConsomeApiQualityGoiania(string ptrsURL) {
            return base.Channel.ConsomeApiQualityGoiania(ptrsURL);
        }
        
        public System.Threading.Tasks.Task<string> ConsomeApiQualityGoianiaAsync(string ptrsURL) {
            return base.Channel.ConsomeApiQualityGoianiaAsync(ptrsURL);
        }
        
        public string GetVersaoWS() {
            return base.Channel.GetVersaoWS();
        }
        
        public System.Threading.Tasks.Task<string> GetVersaoWSAsync() {
            return base.Channel.GetVersaoWSAsync();
        }
        
        public string[] BRASPAG_GetVendaMerchantOrderId(string pstrUrlPost, string pstrContentType, string pstrMethod, string pstrMerchantID, string pstrMerchantKey, string pstrRequestId, string pstrMerchantOrderId) {
            return base.Channel.BRASPAG_GetVendaMerchantOrderId(pstrUrlPost, pstrContentType, pstrMethod, pstrMerchantID, pstrMerchantKey, pstrRequestId, pstrMerchantOrderId);
        }
        
        public System.Threading.Tasks.Task<string[]> BRASPAG_GetVendaMerchantOrderIdAsync(string pstrUrlPost, string pstrContentType, string pstrMethod, string pstrMerchantID, string pstrMerchantKey, string pstrRequestId, string pstrMerchantOrderId) {
            return base.Channel.BRASPAG_GetVendaMerchantOrderIdAsync(pstrUrlPost, pstrContentType, pstrMethod, pstrMerchantID, pstrMerchantKey, pstrRequestId, pstrMerchantOrderId);
        }
        
        public string[] BRASPAG_GetVendaPaymentId(string pstrUrlPost, string pstrContentType, string pstrMethod, string pstrMerchantID, string pstrMerchantKey, string pstrRequestId, string pstrPaymentId) {
            return base.Channel.BRASPAG_GetVendaPaymentId(pstrUrlPost, pstrContentType, pstrMethod, pstrMerchantID, pstrMerchantKey, pstrRequestId, pstrPaymentId);
        }
        
        public System.Threading.Tasks.Task<string[]> BRASPAG_GetVendaPaymentIdAsync(string pstrUrlPost, string pstrContentType, string pstrMethod, string pstrMerchantID, string pstrMerchantKey, string pstrRequestId, string pstrPaymentId) {
            return base.Channel.BRASPAG_GetVendaPaymentIdAsync(pstrUrlPost, pstrContentType, pstrMethod, pstrMerchantID, pstrMerchantKey, pstrRequestId, pstrPaymentId);
        }
        
        public string SetGeraNotaVA_GO(string pstrTipoEndPointClient, string pstrEndPointClient, string pstrBanco, string pstrServidor, string pstrUsuario, string pstrDataInicio, string pstrDataFim, string pstrPathLog) {
            return base.Channel.SetGeraNotaVA_GO(pstrTipoEndPointClient, pstrEndPointClient, pstrBanco, pstrServidor, pstrUsuario, pstrDataInicio, pstrDataFim, pstrPathLog);
        }
        
        public System.Threading.Tasks.Task<string> SetGeraNotaVA_GOAsync(string pstrTipoEndPointClient, string pstrEndPointClient, string pstrBanco, string pstrServidor, string pstrUsuario, string pstrDataInicio, string pstrDataFim, string pstrPathLog) {
            return base.Channel.SetGeraNotaVA_GOAsync(pstrTipoEndPointClient, pstrEndPointClient, pstrBanco, pstrServidor, pstrUsuario, pstrDataInicio, pstrDataFim, pstrPathLog);
        }
        
        public string GetDadosContratoJSON(string pstrCodAssinante, string pstrCodContrato) {
            return base.Channel.GetDadosContratoJSON(pstrCodAssinante, pstrCodContrato);
        }
        
        public System.Threading.Tasks.Task<string> GetDadosContratoJSONAsync(string pstrCodAssinante, string pstrCodContrato) {
            return base.Channel.GetDadosContratoJSONAsync(pstrCodAssinante, pstrCodContrato);
        }
        
        public string GetRamoAtividadeJSON(int pintTipo, int pintSituacao) {
            return base.Channel.GetRamoAtividadeJSON(pintTipo, pintSituacao);
        }
        
        public System.Threading.Tasks.Task<string> GetRamoAtividadeJSONAsync(int pintTipo, int pintSituacao) {
            return base.Channel.GetRamoAtividadeJSONAsync(pintTipo, pintSituacao);
        }
        
        public CWA.Venda.Entity.RamoAtividadeEntity[] GetRamoAtividade(int pintTipo, int pintSituacao) {
            return base.Channel.GetRamoAtividade(pintTipo, pintSituacao);
        }
        
        public System.Threading.Tasks.Task<CWA.Venda.Entity.RamoAtividadeEntity[]> GetRamoAtividadeAsync(int pintTipo, int pintSituacao) {
            return base.Channel.GetRamoAtividadeAsync(pintTipo, pintSituacao);
        }
        
        public string GetCuboClientejcJSON() {
            return base.Channel.GetCuboClientejcJSON();
        }
        
        public System.Threading.Tasks.Task<string> GetCuboClientejcJSONAsync() {
            return base.Channel.GetCuboClientejcJSONAsync();
        }
        
        public CWA.Venda.Entity.CuboClienteJCEntity[] GetCuboClientejc() {
            return base.Channel.GetCuboClientejc();
        }
        
        public System.Threading.Tasks.Task<CWA.Venda.Entity.CuboClienteJCEntity[]> GetCuboClientejcAsync() {
            return base.Channel.GetCuboClientejcAsync();
        }
        
        public string GetCuboAssinaturajcJSON(string psDtInicioInic, string psDtInicioFim) {
            return base.Channel.GetCuboAssinaturajcJSON(psDtInicioInic, psDtInicioFim);
        }
        
        public System.Threading.Tasks.Task<string> GetCuboAssinaturajcJSONAsync(string psDtInicioInic, string psDtInicioFim) {
            return base.Channel.GetCuboAssinaturajcJSONAsync(psDtInicioInic, psDtInicioFim);
        }
        
        public CWA.Venda.Entity.CuboAssinaturaJCEntity[] GetCuboAssinaturajc(string psDtInicioInic, string psDtInicioFim) {
            return base.Channel.GetCuboAssinaturajc(psDtInicioInic, psDtInicioFim);
        }
        
        public System.Threading.Tasks.Task<CWA.Venda.Entity.CuboAssinaturaJCEntity[]> GetCuboAssinaturajcAsync(string psDtInicioInic, string psDtInicioFim) {
            return base.Channel.GetCuboAssinaturajcAsync(psDtInicioInic, psDtInicioFim);
        }
        
        public string GetCuboRecibojcJSON(string psDtInicioInic, string psDtInicioFim) {
            return base.Channel.GetCuboRecibojcJSON(psDtInicioInic, psDtInicioFim);
        }
        
        public System.Threading.Tasks.Task<string> GetCuboRecibojcJSONAsync(string psDtInicioInic, string psDtInicioFim) {
            return base.Channel.GetCuboRecibojcJSONAsync(psDtInicioInic, psDtInicioFim);
        }
        
        public CWA.Venda.Entity.CuboReciboJCEntity[] GetCuboRecibojc(string psDtInicioInic, string psDtInicioFim) {
            return base.Channel.GetCuboRecibojc(psDtInicioInic, psDtInicioFim);
        }
        
        public System.Threading.Tasks.Task<CWA.Venda.Entity.CuboReciboJCEntity[]> GetCuboRecibojcAsync(string psDtInicioInic, string psDtInicioFim) {
            return base.Channel.GetCuboRecibojcAsync(psDtInicioInic, psDtInicioFim);
        }
        
        public string GetCuboProdutojcJSON() {
            return base.Channel.GetCuboProdutojcJSON();
        }
        
        public System.Threading.Tasks.Task<string> GetCuboProdutojcJSONAsync() {
            return base.Channel.GetCuboProdutojcJSONAsync();
        }
        
        public CWA.Venda.Entity.CuboProdutoJCEntity[] GetCuboProdutojc() {
            return base.Channel.GetCuboProdutojc();
        }
        
        public System.Threading.Tasks.Task<CWA.Venda.Entity.CuboProdutoJCEntity[]> GetCuboProdutojcAsync() {
            return base.Channel.GetCuboProdutojcAsync();
        }
        
        public string GetCuboProdAgregjcJSON() {
            return base.Channel.GetCuboProdAgregjcJSON();
        }
        
        public System.Threading.Tasks.Task<string> GetCuboProdAgregjcJSONAsync() {
            return base.Channel.GetCuboProdAgregjcJSONAsync();
        }
        
        public CWA.Venda.Entity.CuboProdAgregJCEntity[] GetCuboProdAgregjc() {
            return base.Channel.GetCuboProdAgregjc();
        }
        
        public System.Threading.Tasks.Task<CWA.Venda.Entity.CuboProdAgregJCEntity[]> GetCuboProdAgregjcAsync() {
            return base.Channel.GetCuboProdAgregjcAsync();
        }
        
        public string GetCuboTipoRecJSON() {
            return base.Channel.GetCuboTipoRecJSON();
        }
        
        public System.Threading.Tasks.Task<string> GetCuboTipoRecJSONAsync() {
            return base.Channel.GetCuboTipoRecJSONAsync();
        }
        
        public CWA.Venda.Entity.CuboTiposRecJCEntity[] GetCuboTiposRecjc() {
            return base.Channel.GetCuboTiposRecjc();
        }
        
        public System.Threading.Tasks.Task<CWA.Venda.Entity.CuboTiposRecJCEntity[]> GetCuboTiposRecjcAsync() {
            return base.Channel.GetCuboTiposRecjcAsync();
        }
        
        public string GetCuboMovRecJSON(string psDtInicioInic, string psDtInicioFim) {
            return base.Channel.GetCuboMovRecJSON(psDtInicioInic, psDtInicioFim);
        }
        
        public System.Threading.Tasks.Task<string> GetCuboMovRecJSONAsync(string psDtInicioInic, string psDtInicioFim) {
            return base.Channel.GetCuboMovRecJSONAsync(psDtInicioInic, psDtInicioFim);
        }
        
        public CWA.Venda.Entity.CuboMovRecJCEntity[] GetCuboMovRecjc(string psDtInicioInic, string psDtInicioFim) {
            return base.Channel.GetCuboMovRecjc(psDtInicioInic, psDtInicioFim);
        }
        
        public System.Threading.Tasks.Task<CWA.Venda.Entity.CuboMovRecJCEntity[]> GetCuboMovRecjcAsync(string psDtInicioInic, string psDtInicioFim) {
            return base.Channel.GetCuboMovRecjcAsync(psDtInicioInic, psDtInicioFim);
        }
        
        public string GetConteudoDestaque(string pstrPathConteudo, string pstrPathImgMKT) {
            return base.Channel.GetConteudoDestaque(pstrPathConteudo, pstrPathImgMKT);
        }
        
        public System.Threading.Tasks.Task<string> GetConteudoDestaqueAsync(string pstrPathConteudo, string pstrPathImgMKT) {
            return base.Channel.GetConteudoDestaqueAsync(pstrPathConteudo, pstrPathImgMKT);
        }
        
        public string GetConteudoPromocao(string pstrPathConteudo, string pstrPathImgMKT) {
            return base.Channel.GetConteudoPromocao(pstrPathConteudo, pstrPathImgMKT);
        }
        
        public System.Threading.Tasks.Task<string> GetConteudoPromocaoAsync(string pstrPathConteudo, string pstrPathImgMKT) {
            return base.Channel.GetConteudoPromocaoAsync(pstrPathConteudo, pstrPathImgMKT);
        }
        
        public string GetConteudoDetalhe(string pstrPathConteudo, string pstrPathImgMKT, int pintIDCampanha, int pintIDPlano) {
            return base.Channel.GetConteudoDetalhe(pstrPathConteudo, pstrPathImgMKT, pintIDCampanha, pintIDPlano);
        }
        
        public System.Threading.Tasks.Task<string> GetConteudoDetalheAsync(string pstrPathConteudo, string pstrPathImgMKT, int pintIDCampanha, int pintIDPlano) {
            return base.Channel.GetConteudoDetalheAsync(pstrPathConteudo, pstrPathImgMKT, pintIDCampanha, pintIDPlano);
        }
        
        public string GetMontarBannerDestaque() {
            return base.Channel.GetMontarBannerDestaque();
        }
        
        public System.Threading.Tasks.Task<string> GetMontarBannerDestaqueAsync() {
            return base.Channel.GetMontarBannerDestaqueAsync();
        }
        
        public string GetRamoAtividadeListJSON(int pintTipoRamo) {
            return base.Channel.GetRamoAtividadeListJSON(pintTipoRamo);
        }
        
        public System.Threading.Tasks.Task<string> GetRamoAtividadeListJSONAsync(int pintTipoRamo) {
            return base.Channel.GetRamoAtividadeListJSONAsync(pintTipoRamo);
        }
        
        public string GetPrecoCampanhaPlanoProdutoJSON(int pintIDCampaha, int pintIDPlano, int pintProduto) {
            return base.Channel.GetPrecoCampanhaPlanoProdutoJSON(pintIDCampaha, pintIDPlano, pintProduto);
        }
        
        public System.Threading.Tasks.Task<string> GetPrecoCampanhaPlanoProdutoJSONAsync(int pintIDCampaha, int pintIDPlano, int pintProduto) {
            return base.Channel.GetPrecoCampanhaPlanoProdutoJSONAsync(pintIDCampaha, pintIDPlano, pintProduto);
        }
        
        public string GetTipoLogradouroListJSON() {
            return base.Channel.GetTipoLogradouroListJSON();
        }
        
        public System.Threading.Tasks.Task<string> GetTipoLogradouroListJSONAsync() {
            return base.Channel.GetTipoLogradouroListJSONAsync();
        }
        
        public string GetViewLogrEntityJSON(string pstrCEP) {
            return base.Channel.GetViewLogrEntityJSON(pstrCEP);
        }
        
        public System.Threading.Tasks.Task<string> GetViewLogrEntityJSONAsync(string pstrCEP) {
            return base.Channel.GetViewLogrEntityJSONAsync(pstrCEP);
        }
        
        public string GetCodRoteirizacaoJSON(int pintIDProduto, int pintIDLogr, int pintNumeroResid) {
            return base.Channel.GetCodRoteirizacaoJSON(pintIDProduto, pintIDLogr, pintNumeroResid);
        }
        
        public System.Threading.Tasks.Task<string> GetCodRoteirizacaoJSONAsync(int pintIDProduto, int pintIDLogr, int pintNumeroResid) {
            return base.Channel.GetCodRoteirizacaoJSONAsync(pintIDProduto, pintIDLogr, pintNumeroResid);
        }
        
        public string GetParametroGlobalWEBJSON() {
            return base.Channel.GetParametroGlobalWEBJSON();
        }
        
        public System.Threading.Tasks.Task<string> GetParametroGlobalWEBJSONAsync() {
            return base.Channel.GetParametroGlobalWEBJSONAsync();
        }
        
        public string GetBandeiraCartaoListJSON() {
            return base.Channel.GetBandeiraCartaoListJSON();
        }
        
        public System.Threading.Tasks.Task<string> GetBandeiraCartaoListJSONAsync() {
            return base.Channel.GetBandeiraCartaoListJSONAsync();
        }
        
        public string GetAdmCartaoListJSON(int pintBandeira) {
            return base.Channel.GetAdmCartaoListJSON(pintBandeira);
        }
        
        public System.Threading.Tasks.Task<string> GetAdmCartaoListJSONAsync(int pintBandeira) {
            return base.Channel.GetAdmCartaoListJSONAsync(pintBandeira);
        }
        
        public string GetAdmCobraGateWayJSON(int pintIDAdmCartao) {
            return base.Channel.GetAdmCobraGateWayJSON(pintIDAdmCartao);
        }
        
        public System.Threading.Tasks.Task<string> GetAdmCobraGateWayJSONAsync(int pintIDAdmCartao) {
            return base.Channel.GetAdmCobraGateWayJSONAsync(pintIDAdmCartao);
        }
        
        public string GetBandeiraCartaoListNovoJSON() {
            return base.Channel.GetBandeiraCartaoListNovoJSON();
        }
        
        public System.Threading.Tasks.Task<string> GetBandeiraCartaoListNovoJSONAsync() {
            return base.Channel.GetBandeiraCartaoListNovoJSONAsync();
        }
        
        public string GetValidarListaNegraJSON(CWA.Venda.Entity.ListaNegraEntity pObjEnt) {
            return base.Channel.GetValidarListaNegraJSON(pObjEnt);
        }
        
        public System.Threading.Tasks.Task<string> GetValidarListaNegraJSONAsync(CWA.Venda.Entity.ListaNegraEntity pObjEnt) {
            return base.Channel.GetValidarListaNegraJSONAsync(pObjEnt);
        }
        
        public string GetContabilContratoJSON(int pintCTR, int pintDVCTR, string pstrSerieCTR) {
            return base.Channel.GetContabilContratoJSON(pintCTR, pintDVCTR, pstrSerieCTR);
        }
        
        public System.Threading.Tasks.Task<string> GetContabilContratoJSONAsync(int pintCTR, int pintDVCTR, string pstrSerieCTR) {
            return base.Channel.GetContabilContratoJSONAsync(pintCTR, pintDVCTR, pstrSerieCTR);
        }
        
        public string GetParametrosPlanoJSON(int pintIDPlano) {
            return base.Channel.GetParametrosPlanoJSON(pintIDPlano);
        }
        
        public System.Threading.Tasks.Task<string> GetParametrosPlanoJSONAsync(int pintIDPlano) {
            return base.Channel.GetParametrosPlanoJSONAsync(pintIDPlano);
        }
        
        public string GetTipoAssinaturaListJSON(int pintIDProduto, int pintIDCampanha) {
            return base.Channel.GetTipoAssinaturaListJSON(pintIDProduto, pintIDCampanha);
        }
        
        public System.Threading.Tasks.Task<string> GetTipoAssinaturaListJSONAsync(int pintIDProduto, int pintIDCampanha) {
            return base.Channel.GetTipoAssinaturaListJSONAsync(pintIDProduto, pintIDCampanha);
        }
        
        public string GetTipoPagamentoListJSON(int pintIDProduto, int pintIDCampanha, int pintIDTipoAssinatura, int pintTipoEntrega) {
            return base.Channel.GetTipoPagamentoListJSON(pintIDProduto, pintIDCampanha, pintIDTipoAssinatura, pintTipoEntrega);
        }
        
        public System.Threading.Tasks.Task<string> GetTipoPagamentoListJSONAsync(int pintIDProduto, int pintIDCampanha, int pintIDTipoAssinatura, int pintTipoEntrega) {
            return base.Channel.GetTipoPagamentoListJSONAsync(pintIDProduto, pintIDCampanha, pintIDTipoAssinatura, pintTipoEntrega);
        }
        
        public string GetBancoDebitoListJSON(int pintIDProdudo) {
            return base.Channel.GetBancoDebitoListJSON(pintIDProdudo);
        }
        
        public System.Threading.Tasks.Task<string> GetBancoDebitoListJSONAsync(int pintIDProdudo) {
            return base.Channel.GetBancoDebitoListJSONAsync(pintIDProdudo);
        }
        
        public string GravarAssinaturaService(CWA.Venda.Entity.DadosPessoaEntity ObjPS, CWA.Venda.Entity.DadosEntregaEntity ObjDE, CWA.Venda.Entity.DadosPagamentoEntity ObjPG) {
            return base.Channel.GravarAssinaturaService(ObjPS, ObjDE, ObjPG);
        }
        
        public System.Threading.Tasks.Task<string> GravarAssinaturaServiceAsync(CWA.Venda.Entity.DadosPessoaEntity ObjPS, CWA.Venda.Entity.DadosEntregaEntity ObjDE, CWA.Venda.Entity.DadosPagamentoEntity ObjPG) {
            return base.Channel.GravarAssinaturaServiceAsync(ObjPS, ObjDE, ObjPG);
        }
        
        public string GravarAbandonoService(string pstrDOC, string pstrEmail, CWA.Venda.Entity.AbandonoEntity pObjEnt, int pintEtapa, int pintStatus, string pstrNuSerieCTR, int pintNuCTR, int pintNuDvCTR) {
            return base.Channel.GravarAbandonoService(pstrDOC, pstrEmail, pObjEnt, pintEtapa, pintStatus, pstrNuSerieCTR, pintNuCTR, pintNuDvCTR);
        }
        
        public System.Threading.Tasks.Task<string> GravarAbandonoServiceAsync(string pstrDOC, string pstrEmail, CWA.Venda.Entity.AbandonoEntity pObjEnt, int pintEtapa, int pintStatus, string pstrNuSerieCTR, int pintNuCTR, int pintNuDvCTR) {
            return base.Channel.GravarAbandonoServiceAsync(pstrDOC, pstrEmail, pObjEnt, pintEtapa, pintStatus, pstrNuSerieCTR, pintNuCTR, pintNuDvCTR);
        }
        
        public string GetAbandonoLojaService(string pstrDOC, int pintTipo) {
            return base.Channel.GetAbandonoLojaService(pstrDOC, pintTipo);
        }
        
        public System.Threading.Tasks.Task<string> GetAbandonoLojaServiceAsync(string pstrDOC, int pintTipo) {
            return base.Channel.GetAbandonoLojaServiceAsync(pstrDOC, pintTipo);
        }
        
        public string SendMailAPI(string pstrUrlBasePOST, string pstrAPIKey, string pstrDomain, string pstrFromMail, string pstrToMail, string pstrSubject, string pstrText, int pintTipoEmail, string pstrPathAnexo, string pstrFileAnexo) {
            return base.Channel.SendMailAPI(pstrUrlBasePOST, pstrAPIKey, pstrDomain, pstrFromMail, pstrToMail, pstrSubject, pstrText, pintTipoEmail, pstrPathAnexo, pstrFileAnexo);
        }
        
        public System.Threading.Tasks.Task<string> SendMailAPIAsync(string pstrUrlBasePOST, string pstrAPIKey, string pstrDomain, string pstrFromMail, string pstrToMail, string pstrSubject, string pstrText, int pintTipoEmail, string pstrPathAnexo, string pstrFileAnexo) {
            return base.Channel.SendMailAPIAsync(pstrUrlBasePOST, pstrAPIKey, pstrDomain, pstrFromMail, pstrToMail, pstrSubject, pstrText, pintTipoEmail, pstrPathAnexo, pstrFileAnexo);
        }
    }
}
